**Python Is a Case Sensitive Programming Language.**

**Python Is a Simple Calculator.**

**Disadvantages of Python**
1. Slow speed
2. Communication with other programming languages is weak

**Python Editors:**
- Pycharm
- Spyder
- Wing
- IDLE
- Atom
- VS Code

**Naming variables:**
1. The number must not be prime.
2. Symbols are not used in variable names.
   1. Only underline is allowed.

**Python's types:**
- Integer(int)
- Float
- String(str)
- List
- Bool
- Set
- Dictionary

**Types of printing:**

- Comma(,)
- Sum of strings
- %s
- .Format

**If condition:**
```
if cond 1:
    ------
    ------
    ------
else:
    ------
    ------
    ------
```

**Example of Condition:**
```
if x <= 0:
    print('You Number Is Not Valid.')
else:
    if x > 0 and x <= 9:
        print('Adad 1 Raghami Ast.')
    elif x >= 10 and x <= 99:
        if x == 22:
            print('Are You Sara?')
        print('Adad 2 Raghami Ast.')
    elif 100 <= x <= 999:
        print('Adad 3 Raghami Ast.')
```

**Collection Built-in:**
1. List ----> [ ]
2. Tuple ----> ( )
3. Set ----> { }
4. Dictionary ----> { }

**1. List:**

- Members are separated by commas.
- Members of a list can have any types.

**Index [ ]:**

- A list has an index with all its members.
- The index starts from zero.

**List methods:**

- Len ---> The number of list members.
- .append() ---> Add a member to the list.
- .remove() ---> Deletes the first value.
- clear() ---> Deletes the members of the list.
- .pop() ---> The last member is removed and can be stored in a variable.
- .sort() ---> Sorts numbers from small to large.

**Examples of List:**
```
l1 = [1, 2, 3]
print('l1:', l1)
print('type(l1):', type(l1))
l2 = [1, 2.5, 'Python', True, False, [-5, 3.14]]
print('l2:', l2)
print('type(l2):', type(l2))
l3 = list((1, 2, 3))
print('l3:', l3)
print('type(l3):', type(l3))
print('=====================================')

l4 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]
# l4 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print('l4:', l4)
print('type(l4):', type(l4))
print('=====================================')

x = 6.4
y = True
t = 'Beheshti'
l5 = [x, y, t, l3, 4]
print('l5:', l5)
print('=====================================')
# Indexing
# Slicing
l6 = [8, 6, 1, 3, -8, 7, 4, 6, -13, 1, -5, 4]
print('l6:', l6)
print('l6[0]:', l6[0])
print('l6[5]:', l6[5])
print('l6[8]:', l6[8])
print('l6[2]:', l6[2])
#  print('l6[20]:', l6[20])  --> IndexError: list index out of range
print('l6[-1]:', l6[-1])
print('l6[-4]:', l6[-4])
print('l6[2:7]:', l6[2:7])
print('l6[8:11]:', l6[8:11])
print('l6[8:-1]:', l6[8:-1])
print('l6[8:]:', l6[8:])
print('l6[:5]:', l6[:5])  # l6[0:5]
print('l6[:]:', l6[:])
print('l6[1:-1:2]:', l6[1:-1:2])
print('l6[1::3]:', l6[1::3])
print('l6[::2]:', l6[::2])
print('l6[::-1]:', l6[::-1])
print('=====================================')
l7 = [True, 4, 9.5, 'Python', [5, 8, 9]]
x = l7[2]
print('x = l7[2]:', x)
l7[1] = 3.6
print('l7:', l7)
print('l7[-1]:', l7[-1])
print('l7[-1][1]:', l7[-1][1])
print('=====================================')

a = [1]
b = [1]
print(a is b)
print(a[0] is b[0])
print('=====================================')
l8 = [True, 4, 9.5, 'Python', [5, 8, 9]]
if 9.5 in l8:
    print('Yes')
else:
    print('No')

print('len(l8):', len(l8))
l8.append(6)
print('l8 After append:', l8)
l8.remove(4)
print('l8 After remove:', l8)
l9 = [1, 2, 3, 4, 1, 5, 1]
l9.remove(1)
print('l9 after remove:', l9)
del l9[3]
print('l9 after del one index:', l9)
l9.insert(2, 'Python')
print('l9 after insert:', l9)
l9.clear()
print('l9 after clear:', l9)
del l9
# print('l9 after del list:', l9)  --> NameError: name 'l9' is not defined

l10 = [True, 4, 9.5, 'Python', [5, 8, 9]]
x = l10.pop()
print('x:', x)
print('l10 after pop:', l10)
print('=====================================')

l11 = [8, 6, 1, 3, -8, 7, 4, 6, -13, 1, -5, 4]
# l11.sort()
l12 = sorted(l11)
print('l11 after sorted:', l11)
print('l12 after sorted:', l12)

print('=====================================')

l = [1, 2, 3]
r = [4, 5, 6, 4]
a = l + r
print('a = l + r:', a)
i = a.index(4)
print('i:', i)
a.sort(reverse=True)
print('a after reversed sort:', a)
```

**2. Tuple**

- It is used to store multiple values in a variable.
- A tuple is not mutable.

**Examples of Tuple:**
```
t1 = (1, 2, 3)
print('t1:', t1)
print('type(t1):', type(t1))
print('len(t1):', len(t1))
print('+++++++++++++++++++++++++++++++++')

t2 = tuple((4, 5, 6))
print('t2:', t2)
print('type(t2):', type(t2))

print('+++++++++++++++++++++++++++++++++')

t3 = (2.7, 1, True, 'Sara', [1, 2], (2, 3))
print('t3:', t3)
print('type(t3):', type(t3))
print('len(t3):', len(t3))
print('t3[4]:', t3[4])
print('t3[5][-1]:', t3[5][-1])
print('t3[2:5]:', t3[2:5])
print('t3[2:]:', t3[2:])
print('t3[:-2]:', t3[:-2])
print('+++++++++++++++++++++++++++++++++')

t4 = (4, 6, 8, 2, 5, 3, 9, 1, 4, 7)
print('t4:', t4)
t5 = t4[::-1]
print('t5:', t5)
l4 = list(t4)
l4[8] = 0
t4 = tuple(l4)
# t4[8] = 0  --> Error
print('t4:', t4)
print('+++++++++++++++++++++++++++++++++')
t6 = ('Python', 'Matlab', 'JavaScript',
      'PHP', 'C#', 'Java', 'C++')
l6 = list(t6)
l6.append('Shell')
t6 = tuple(l6)
print('t6:', t6)
print('+++++++++++++++++++++++++++++++++')
t7 = (4,)
print('t7:', t7)
print(type(t7))
print('+++++++++++++++++++++++++++++++++')
t8 = (1, 2, 3)
t9 = (4, 5, 6)
t10 = (7, 8, 9)
t11 = t8 + t9 + t10
print('t11:', t11)
t12 = ((1, 2, 3, 4),)
print('len(t12):', len(t12))
```

**3. Set:**
1. It must have been sorted.
2. It does not have duplicate members.

**Set methods:**

- .add() ---> Add a member to the list.
- .updates() ---> Make changes.
- .remove() ---> Delete a member.
- .discard() ---> Delete a member.
- .union() or | ---> Union.
- .intersection or & ---> Intersection.

**Examples of Set:**
```
s1 = {8, 5, 1, 2, 6, 4.6, 8.5, 2, 1, 2, 2, 2}
print('s1:', s1)
print('type(s1):', type(s1))
print('len(s1):', len(s1))
s1.add(3)
print('s1 after add():', s1)
s2 = {3, 1, 2}
s3 = {5, 4, 3}
s2.update(s3)
print('s2 after update():', s2)
s2.remove(4)
print('s2 after remove():', s2)
s2.discard(2)
print('s2 after discard():', s2)
s2.clear()
print('s2 after clear():', s2)
del s2
# print('s2 after del:', s2)  --> Error

s4 = {3, 1, 2}
s5 = {5, 4, 3}
s6 = s4.union(s5)
print('s6:', s6)
x = s6.pop()
print('s6 after pop():', s6)
print('x = s6.pop():', x)

l = [1, 2, 3, 1, 2, 6, 4, 5, 2, 9, 9, 8, 1, 4]
l = list(set(l))
print('l:', l)
s7 = {1, 2, 3}
s8 = {4, 1, 6}
s9 = s7.union(s8)
s10 = s7.intersection(s8)
s11 = s7.difference(s8)
s12 = s7.symmetric_difference(s8)

print('s9 = s7.union(s8):', s9)
print('s10 = s7.intersection(s8):', s10)
print('s11 = s7.difference(s8):', s11)
print('s12 = s7.symmetric_difference(s8):', s12)
print('s7 & s8:', s7 & s8)  # intersection
print('s7 | s8:', s7 | s8)  # union
```

**4. Dictionary:**
```
d = {
     k1:v1,
     k2:v2,
     k3:v3
}

d[k]---> v
```

**Examples of Dictionary:**
```
d1 = {
    'hello': 'salam',
    'bye': 'khodahafez',
    'book': 'ketab'
}

print('d1:', d1)
print('type(d1):', type(d1))
print("d1['hello']:", d1['hello'])
print("d1['bye']:", d1['bye'])
print("d1['book']:", d1['book'])
d1['class'] = 'kelas'
print('d1:', d1)
print("d1['class']:", d1['class'])
d1['bye'] = 'bedrood'
print('d1:', d1)

x = d1['bye']
print('x:', x)
y = d1.get('hello')
print('y:', y)

k = d1.keys()
print('k:', k)
print('type(k):', type(k))
v = d1.values()
print('v:', v)
print('type(v):', type(v))
print('===============================')
user = {
    'fname': 'Farzad',
    'lname': 'Asgari',
    'age': 27,
    'height': 185,  # Cm
    'birthday': '75/06/15',
}

print('user:', user)
user['weight'] = 77  # Kg
print('user after adding weight:', user)
print('===============================')

d2 = {
    0: [0, -1, -2],
    1: [1, 2, 3],
}
print('d2:', d2)
print('d2[1]:', d2[1])
```

**Loops:**
They are used to avoid repeating the code.
1. For ---> The number of repetitions is specified.
2. While ---> The number of repetitions is unknown.

**1. For loop:**
```
for block
for _____ in ______:    
    ___________
    ___________
```

**Example of For Loops:**
```
for counter in [True, 'Meysam', 2.5, 6, [1, 2]]:
    print(counter, type(counter))

print('After Loop!')
print('============================')
# counter
# i
# j
# q
# c
# r
# count
# char

names = ('Saeed', 'Farzad', 'Arsham', 'Meysam',
         'Sara', 'Armita')

for name in names:
    print(name)

print('============================')

language_name = 'Python'
for char in language_name:
    print('Char is Equal to: %s' % char)


for i in ' '*10:
    print('khufarzadasgari@gmail.com')
print('============================')

for i in range(10):
    print(i)

print('============================')

for i in range(3, 6):
    print(i)
```

**2. While loop:**
```
while condition:
    _________
    _________

    Break
```

**Example of While Loops:**
```
x = 5
while x > 0:
    print(x)
    x = x - 1

print('End While')
print('================')
l = [5, 8, 4, 1, 6]
# for i in l:
#     print(i)
i = 0
while i < len(l):
    print(l[i])
    i = i + 1
```

**Functional Programming:**

- Increases Speed
- It Allows Programmers To Work Together On a Project.
  
  ```
  def plus(a, b):
    r = a + b
    return r
  x = plus(8, 5)
  y = plus(4, -5)
  print('x:', x)
  print('y:', y)
  ```